### ISSUE TITLE
Verify that a property exists when loading it from defaults.yaml and env.yaml

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#201]
We should validate the values we import from the configuration file so that we spot errors (such as wrongly spelled keys) early on.

Ideally, we should do this such as a simple `vagrant status` reports errors, so that we piggyback on existing checks during CI

**Comment by StefanoSalsano** [comment]
ok but recently I have introduced the approach of adding new keys into the settings:

for example with this yaml

```yaml
ansible:
  group_vars:
    all:
      kubernetes_network_plugin_options:
        no-cni-plugin: false
        calico: true
        weavenet: false
        flannel: false
```
Vagrantfile will create a new key, which was not present in the yaml:
`settings["ansible"]["group_vars"]["all"]["kubernetes_network_plugin"]`

I don't know how you plan to validate, but we should keep the above into account... 
and there are solutions with different over-engineering factors ;-)
