### ISSUE TITLE
Use Ansible instead of relying on shell scripts for configuration

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#76]
We should get rid of the following scripts, and use Ansible instead:

- [ ] - `cleanup-k8s-and-cni.sh`
- [x] - `configure-ipv6-interface.sh`
- [ ] - All Kubernetes workloads bootstrapping scripts. We can use the [Ansible k8s module](https://docs.ansible.com/ansible/latest/modules/k8s_module.html).
- [x] `check-kubeadm-requirements.sh`

# Useful for check-kubeadm-requirements.sh

```yaml
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
```
